title: "Climate Studio Workshops"
author: "Amber Sun ME'27"
copyright: "2026, Amber, advised by Prof. Melody Baglione"

only_build_toc_files: true

exclude_patterns:
  - workshops/downloads/**
  - workshops/static/**
  - README.md
  - LICENSE
  - .gitignore

html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

repository:
  url: https://github.com/amber289/climatestudiotutorial
  branch: main

execute:
  execute_notebooks: "off"
